#!/bin/bash

echo "🚀 开始部署 V8.3.21.11 到服务器..."
echo ""
echo "请在服务器上执行以下命令："
echo ""
echo "=========================================="
echo "cd /root/10-23-bot"
echo "git reset --hard"
echo "git pull"
echo "bash ~/快速重启_修复版.sh all"
echo "=========================================="
echo ""
echo "✅ 本次修复内容："
echo "  1. Qwen邮件主题添加模型名称前缀"
echo "  2. DeepSeek邮件主题去掉双重前缀"
echo ""
echo "✅ 语法验证：已通过"
echo "✅ 版本：V8.3.21.11（基于稳定版V8.3.21.5）"
echo ""
echo "📝 或者直接SSH登录服务器："
echo "ssh -o ProxyCommand=\"nc -X 5 -x 127.0.0.1:7890 %h %p\" root@43.100.52.142"
echo "密码：j1lUcf9TbdCzZkPL"

